import { jsPDF } from 'jspdf';
import type { CircuitProject } from '../types';

class PDFExportServiceClass {
  async generateSummary(project: CircuitProject, finalDiagram?: string): Promise<Blob> {
    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
    const W = 210;
    const MARGIN = 18;
    const LINE = 7;
    let y = MARGIN;

    const writeLine = (text: string, size = 11, style: 'normal' | 'bold' = 'normal', color = '#191b23') => {
      doc.setFontSize(size);
      doc.setFont('helvetica', style);
      doc.setTextColor(color);
      const lines = doc.splitTextToSize(text, W - MARGIN * 2) as string[];
      lines.forEach((line) => {
        if (y > 270) {
          doc.addPage();
          y = MARGIN;
        }
        doc.text(line, MARGIN, y);
        y += LINE;
      });
    };

    const gap = (n = 1) => { y += LINE * n * 0.5; };

    // Title
    writeLine('SkillForge — Circuit Summary', 20, 'bold', '#004ac6');
    gap();
    writeLine(project.title, 16, 'bold');
    writeLine(project.description, 10, 'normal', '#434655');
    gap();

    writeLine(`Difficulty: ${project.difficulty}  |  Category: ${project.category}${project.isExperimental ? '  |  Experimental' : ''}`, 9, 'normal', '#737686');
    gap(2);

    // Components
    writeLine('Required Components', 13, 'bold');
    doc.setDrawColor('#c3c6d7');
    doc.line(MARGIN, y, W - MARGIN, y);
    y += 4;
    project.requiredComponents.forEach((comp) => {
      writeLine(`• ${comp.physicalLabel}  (${comp.category})`, 10);
    });
    gap(2);

    // Steps
    writeLine('Step-by-Step Instructions', 13, 'bold');
    doc.line(MARGIN, y, W - MARGIN, y);
    y += 4;

    project.steps.forEach((step) => {
      writeLine(`Step ${step.number}: ${step.title}`, 11, 'bold');
      writeLine(step.instruction, 10);
      if (step.connections.length > 0) {
        writeLine('Connections:', 9, 'bold', '#004ac6');
        step.connections.forEach((conn) => {
          writeLine(
            `  ${conn.sourceComponentId}[${conn.sourceTerminalId}] → ${conn.targetComponentId}[${conn.targetTerminalId}]`,
            9,
            'normal',
            '#434655',
          );
        });
      }
      if (step.diagramFallback) {
        writeLine('Diagram:', 9, 'bold', '#737686');
        writeLine(step.diagramFallback, 8, 'normal', '#434655');
      }
      gap();
    });

    // Final diagram image if available
    if (finalDiagram && finalDiagram.startsWith('data:image')) {
      if (y > 220) { doc.addPage(); y = MARGIN; }
      writeLine('Final Circuit Diagram', 13, 'bold');
      gap();
      try {
        doc.addImage(finalDiagram, 'PNG', MARGIN, y, W - MARGIN * 2, 60);
        y += 65;
      } catch {
        writeLine('[Image could not be embedded]', 9, 'normal', '#ba1a1a');
      }
    }

    gap(2);
    doc.setFontSize(8);
    doc.setTextColor('#737686');
    doc.text(`Generated by SkillForge on ${new Date().toLocaleDateString()}`, MARGIN, y);

    return doc.output('blob');
  }
}

export const pdfExportService = new PDFExportServiceClass();
